language: go
go:
- 1.5.3
- tip


before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}


script:
- go test -v -p=1 -race -timeout=90s github.com/dropbox/kafka/...
- go vet github.com/dropbox/kafka/...
- go test -bench '.*' -run none github.com/dropbox/kafka/...

env:
- WITH_INTEGRATION=false GOMAXPROCS=4

sudo: false
